media:
  input: docs/blog/images
  output: /blog/images
content:
  - name: posts
    label: Posts
    type: collection
    path: 'docs/blog/posts'
    view:
      fields: [ title, date, categories, slug, draft ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: categories
        label: Categories
        type: string
        list:
          min: 1
          max: 4
        options:
          values: [ github, life, notion, open-source, research, vision ]
        required: false
      - name: slug
        label: Slug
        type: string
        required: true
      - name: body
        label: Body
        type: rich-text
      - name: draft
        label: Draft
        type: boolean
        default: true