site_name: Spencer Woo
site_description: Spencer's personal blog and website
site_url: https://spencerwoo.com
copyright: Copyright &copy; 2020 - Present @ Spencer Woo

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
  - Publications: publications.md
  - Sponsor: sponsor.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  # font:
  #   text: Playfair Display
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to system preference

  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.prune
    - navigation.footer
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - search.suggest
    - content.action.edit
    - content.code.copy

extra:
  analytics:
    provider: google
    property: G-1L6PZQPYZ9
  social:
    - icon: material/rss-box
      link: /feed.xml

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - search
  - awesome-pages
  - blog:
      post_url_format: "{slug}"
  # - social
  - rss:
      match_path: "blog/posts/.*"
      feeds_filenames:
        json_created: feed.json
        json_updated: feed_updated.json
        rss_created: feed.xml
        rss_updated: feed_updated.xml
      date_from_meta:
        as_creation: "date"
        as_update: "date_updated"
      use_git: false
      abstract_delimiter: <!-- more -->
